### ISSUE TITLE
Smart way to use @ApiQuery()

### ISSUE THREAD

**Issue by ngankhanh98** [ngankhanh98/coursebox-server#1]
### Hiện tại chạy ổn:
Route /teacher/search?... đã cho phép search với 2 fields `teacher_id` hoặc/và `fullname`
![image](https://user-images.githubusercontent.com/32817908/99056930-9b5cb680-25cd-11eb-8ebf-bc3561f48c22.png)
Log được
![image](https://user-images.githubusercontent.com/32817908/99057541-846a9400-25ce-11eb-8778-9d79a5c0b226.png)
Trong code để swagger hiện lên 2 fields cho điền, thì cần 
```ts
...
 @Get('/search')
  // FIXME: how to shorten @ApiQuery, what if users are let to query with 100 filter \O/
  @ApiQuery({ name: 'teacher_id', required: false})
  @ApiQuery({ name: 'fullname', required: false })
  async find(@Query('') filter: string) {
    console.log('filter', filter);
  }
```

###Vấn đề là
Sau này có thể sẽ cho phép search với nhiều filter khác, như exp=3yrs, tag=web... nên sẽ cần thêm `@ApiQuery()` nữa, vậy có cách nào viết ngắn `@ApiQuery({name: [<list>], required:false})` không ạ anh @dohoangdinhtien

**Comment by dohoangdinhtien** [comment]
Hi @ngankhanh98,
Yes em. Nếu với case mà filter e muốn chỉ rõ là search bằng gì thì em sẽ viết vậy.
Nhưng với case giả sử muốn filter nhiều fields hơn, thì phải thống nhất cách filter. Em có thể xem cách filter bên nestjs/crud để tìm hiểu.

**Comment by dohoangdinhtien** [comment]
Please see detail at https://github.com/nestjsx/crud/wiki/Requests#query-params

**Comment by ngankhanh98** [comment]
Dạ, đã hiểu, em cảm ơn anh Tiến
